name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
  check_suite:
    types:
      - completed
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: pascalgn/automerge-action@v0.14.3
        env:
          GITHUB_TOKEN: '${{ secrets.AUTO_MERGE_TOKEN }}'
          MERGE_LABELS: ':rocket: Ready to Merge,!:warning: Blocked'
          MERGE_COMMIT_MESSAGE: pull-request-title
          UPDATE_LABELS: ':rocket: Ready to Merge'
          UPDATE_METHOD: rebase
          MERGE_FORKS: 'false'
